"""Leaderboard: aggregate every results/*/eval_metadata.json into one table.

Usage: python compare.py
Writes results/leaderboard.md (sorted by PR-AUC) and prints it.
Stdlib-only so it runs anywhere, including this laptop.
"""
import json
import sys
from pathlib import Path

# Git Bash consoles default to cp1252, which can't print "→" — force UTF-8
# so the table prints instead of crashing after the file is written.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

RESULTS = Path(__file__).parent / "results"

rows = []
for meta_path in sorted(RESULTS.glob("*/eval_metadata.json")):
    m = json.loads(meta_path.read_text())
    cfg = m.get("config", {})
    rows.append({
        "run": meta_path.parent.name,
        "pr_auc": m.get("pr_auc"),
        "roc_auc": m.get("roc_auc"),
        "ne": m.get("normalized_entropy"),
        "calibration": m.get("calibration_ratio"),
        "train_s": m.get("train_seconds"),
        "cols": cfg.get("n_input_columns"),
        "penalty": cfg.get("penalty", "l2"),
        "commit": m.get("git_commit", "?"),
    })

rows.sort(key=lambda r: r["pr_auc"] or 0, reverse=True)

lines = [
    "# Leaderboard",
    "",
    "All metrics are train-eval (see README → Evaluation protocol). "
    "Auto-generated by compare.py — do not edit.",
    "",
    "| Run | PR-AUC | ROC-AUC | NE | Calibration | Train s | Cols | Penalty | Commit |",
    "|---|---|---|---|---|---|---|---|---|",
]
for r in rows:
    lines.append(
        f"| {r['run']} | {r['pr_auc']:.4f} | {r['roc_auc']:.4f} | {r['ne']:.3f} "
        f"| {r['calibration']:.2f} | {r['train_s']} | {r['cols'] or '?'} "
        f"| {r['penalty']} | {r['commit']} |"
    )

out = "\n".join(lines) + "\n"
(RESULTS / "leaderboard.md").write_text(out, encoding="utf-8")
print(out)
